project:
  type: website

website:
  title: "Creators for Gaza"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sign-up-form.qmd
        text: Sign-up Form
      - href: donations-data.qmd
        text: Fundraising information
      # - href: dashboard.qmd
      #   text: Dashboard 

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true



