project:
  type: website

website:
  title: "CREATORS\nFOR GAZA"
  favicon: images/cfg-logo-new.jpg
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    logo: images/cfg-logo-new.jpg
    left:
      - href: home/index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: volunteer.qmd
        text: Volunteer
      - href: donations-data.qmd
        text: Our Families
      - href: resources.qmd
        text: Links
    tools:
      - icon: instagram
        href: https://www.instagram.com/creatorsforgaza
      # - href: dashboard.qmd
      #   text: Dashboard 

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true



