project:
  type: website

website:
  title: "Creators for Gaza"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Sign-up Form
      # - href: dashboard.qmd
      #   text: Dashboard 

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true



