---
title: "OUR PALESTINIAN FAMILIES’ FUNDRAISERS"
execute:
  message: false
  error: false
  warning: false
  echo: false
format: 
  html:
    toc: false
    # link-external-icon: true
    link-external-newwindow: true
---



```{r}

library(tidyverse)
library(googledrive)
library(googlesheets4)
library(rvest)
library(bslib)
library(bsicons)
library(gt)

library(gtExtras)

```


```{r}
##| cache: true
# 
source("gfm-data.R")

```




```{r cleaning df}
#| echo: false
#| include: false


x <- test_tib %>% 
  dplyr::filter(!is.na(total_goal_amount))

# final_table <-  x %>% 
#   dplyr::mutate(amount_raised_num = parse_number(money_raised)) %>% 
#   dplyr::mutate(currency = str_extract(money_raised, "[€|$|kr|£]")) %>% 
#   dplyr::mutate(currency_abv = dplyr::case_when(
#     currency == "$" & is_canadian == FALSE ~ "USD",
#     currency == "$" & is_canadian == TRUE ~ "CAD",    
#     currency == "€" ~ "EUR",
#     currency == "£" ~ "GBP",
#     currency == "k" & link == 
#       "https://www.gofundme.com/f/4-months-separates-between-life-and-death-and-we" ~ "SEK",
#     currency == "k" & link == "https://www.gofundme.com/f/help-my-sister-and-her-family-escape-the-war-in-gaza" ~ "NOK",
#     TRUE ~ NA_character_
#   )) %>% 
#   dplyr::mutate(percent_of_goal = amount_raised_num / total_goal_amount*100) %>% 
#   dplyr::mutate(fund_parameter = str_sub(link, start = 28L)) %>% 
#   dplyr::left_join( sheet_gaza %>% 
#                       # removing fund with broken link for now
#                       janitor::clean_names() %>% 
#                      dplyr::select(1:2, status, fund_parameter),
#                    by = "fund_parameter") %>% 
#   dplyr::arrange(desc(status), percent_of_goal) %>%  
#   dplyr::mutate(link_text = str_wrap(gfm_link, width = 18)) %>% 
#   # dplyr::mutate(uuid = str_sub(link, start = 19L)) %>% 
#   dplyr::select(link, link_text,
#                 total_num_donations,currency_abv, amount_raised_num, 
#                 percent_of_goal, 
#                 total_num_donations_24_hours:money_raised_24_hours)



```


```{r removing daily numbers from table}
#| echo: false
#| include: false

final_table1 <-  x %>% 
  dplyr::mutate(amount_raised_num = money_raised) %>% 
  # dplyr::mutate(currency = str_extract(money_raised, "[€|$|kr|£]")) %>% 
  dplyr::mutate(currency_abv = case_when(
    currency == "Other" ~ "NOK",
    TRUE ~ currency)) %>% 
  dplyr::mutate(percent_of_goal = amount_raised_num / total_goal_amount*100) %>% 
  dplyr::mutate(fund_parameter = str_sub(link, start = 28L)) %>% 
  dplyr::left_join( sheet_gaza %>% 
                      # removing fund with broken link for now
                      janitor::clean_names() %>% 
                     dplyr::select(1:2, status, fund_parameter),
                   by = "fund_parameter") %>%
  dplyr::arrange(desc(status), percent_of_goal) %>%  
  dplyr::mutate(link_text = str_wrap(gfm_link, width = 18)) %>% 
  # dplyr::mutate(uuid = str_sub(link, start = 19L)) %>% 
  dplyr::select(fund_parameter, link, link_text,
                total_num_donations,currency_abv, amount_raised_num, 
                percent_of_goal)


```


```{r}

data_write_back <- final_table1 %>% 
  dplyr::mutate(link = str_sub(link, start = 28L)) %>% 
  dplyr::select(link, amount_raised_num, total_num_donations) %>% 
  dplyr::mutate(date = now()) 


googlesheets4::sheet_append(
    ss = ss1,
    sheet = "data",
    data = data_write_back
  )

```


```{r adding daily numbers}

sheet_gaza_data <- read_sheet(ss1,
                              sheet = "data")

num_funds <- nrow(all_gfm_links) 

daily_numbers <- sheet_gaza_data %>% 
  dplyr::filter(date > today() - days(4)) %>% 
  dplyr::arrange(desc(date)) %>% 
  dplyr::group_by(link) %>% 
  dplyr::mutate(row_n = row_number()) %>% 
  dplyr::ungroup() %>% 
  dplyr::filter(row_n %in% c(1,2)) %>% 
  # dplyr::filter(date > as.Date("2024-09-13")) %>% 
  dplyr::arrange(link, date) %>% 
  dplyr::mutate(lagged_val = lag(amount_raised_num)) %>% 
  dplyr::mutate(daily_change = amount_raised_num - lagged_val) %>% 
  dplyr::mutate(filt_this = rep(c(FALSE, TRUE), num_funds)) %>% 
  dplyr::filter(filt_this == TRUE) %>% 
  dplyr::select(link, daily_change)

final_table <- final_table1 %>% 
  dplyr::left_join(daily_numbers,
                   join_by(fund_parameter == link)) %>% 
  dplyr::select(-fund_parameter)

```


```{r sum of currencies}
sum_all_donations_in_usd <- final_table %>%
  dplyr::filter(currency_abv == "USD") %>% 
  summarise(sum(amount_raised_num)) %>%
  as.numeric() %>%
  format(big.mark = ",")

sum_all_donations_in_usd_24 <- final_table %>%
  dplyr::filter(currency_abv == "USD") %>% 
  summarise(sum(daily_change)) %>%
  as.numeric() %>%
  format(big.mark = ",")

sum_all_donations_in_cad <- final_table %>%
  dplyr::filter(currency_abv == "CAD") %>% 
  summarise(sum(amount_raised_num)) %>%
  as.numeric() %>%
  format(big.mark = ",")

sum_all_donations_in_cad_24 <- final_table %>%
  dplyr::filter(currency_abv == "CAD") %>% 
  summarise(sum(daily_change)) %>%
  as.numeric() %>%
  format(big.mark = ",")

sum_all_donations_in_eur <- final_table %>%
  dplyr::filter(currency_abv == "EUR") %>% 
  summarise(sum(amount_raised_num)) %>%
  as.numeric() %>%
  format(big.mark = ",")


sum_all_donations_in_eur_24 <- final_table %>%
  dplyr::filter(currency_abv == "EUR") %>% 
  summarise(sum(daily_change)) %>%
  as.numeric() %>%
  format(big.mark = ",")

sum_all_donations_in_gbp <- final_table %>%
  dplyr::filter(currency_abv == "GBP") %>% 
  summarise(sum(amount_raised_num)) %>%
  as.numeric() %>%
  format(big.mark = ",")

sum_all_donations_in_gbp_24 <- final_table %>%
  dplyr::filter(currency_abv == "GBP") %>% 
  summarise(sum(daily_change)) %>%
  as.numeric() %>%
  format(big.mark = ",")

sum_all_donations_in_sek <- final_table %>%
  dplyr::filter(currency_abv == "SEK") %>% 
  summarise(sum(amount_raised_num)) %>%
  as.numeric() %>%
  format(big.mark = ",")

sum_all_donations_in_sek_24 <- final_table %>%
  dplyr::filter(currency_abv == "SEK") %>% 
  summarise(sum(daily_change)) %>%
  as.numeric() %>%
  format(big.mark = ",")

sum_all_donations_in_nok <- final_table %>%
  dplyr::filter(currency_abv == "NOK") %>% 
  summarise(sum(amount_raised_num)) %>%
  as.numeric() %>%
  format(big.mark = ",")

sum_all_donations_in_nok_24 <- final_table %>%
  dplyr::filter(currency_abv == "NOK") %>% 
  summarise(sum(daily_change)) %>%
  as.numeric() %>%
  format(big.mark = ",")

num_funds_usd <- final_table %>%
  dplyr::filter(currency_abv == "USD") %>% 
  nrow()

num_funds_usd_24 <- final_table %>%
  dplyr::filter(currency_abv == "USD") %>% 
  dplyr::filter(daily_change > 0.01) %>% 
  nrow()

num_funds_cad <- final_table %>%
  dplyr::filter(currency_abv == "CAD") %>% 
  nrow()

num_funds_cad_24 <- final_table %>%
  dplyr::filter(currency_abv == "CAD") %>% 
  dplyr::filter(daily_change > 0.01) %>% 
  nrow()

num_funds_euro <- final_table %>%
  dplyr::filter(currency_abv == "EUR") %>% 
  nrow()

num_funds_euro_24 <- final_table %>%
  dplyr::filter(currency_abv == "EUR") %>% 
  dplyr::filter(daily_change > 0.01) %>% 
  nrow()

num_funds_gbp <- final_table %>%
  dplyr::filter(currency_abv == "GBP") %>% 
  nrow()

num_funds_gbp_24 <- final_table %>%
  dplyr::filter(currency_abv == "GBP") %>% 
  dplyr::filter(daily_change > 0.01) %>% 
  nrow()

num_funds_sek <- final_table %>%
  dplyr::filter(currency_abv == "SEK") %>% 
  nrow()

num_funds_sek_24 <- final_table %>%
  dplyr::filter(currency_abv == "SEK") %>% 
  dplyr::filter(daily_change > 0.01) %>% 
  nrow()

num_funds_nok <- final_table %>%
  dplyr::filter(currency_abv == "NOK") %>% 
  nrow()

num_funds_nok_24 <- final_table %>%
  dplyr::filter(currency_abv == "NOK") %>% 
  dplyr::filter(daily_change > 0.01) %>% 
  nrow()

```


```{r}
# 
# library(qrcode)
# 
# 
# links_qr <- all_gfm_links %>%
#   dplyr::select(link = links)
# 
# row_n_qr <- final_table %>%
#   dplyr::select(uuid)
# 
# 
# for(i in 1:num_funds){
# 
#   link = as.character(links_qr[i,1])
# 
#   rn = as.character(row_n_qr[i,1])
# 
#   png(filename = str_glue("qr-codes/{rn}.png"))
# 
#   plot(qr_code(link ,
#         ecl = "Q") %>%
#   qrcode::add_logo(
#     logo = "images/cfg-logo-new.png",
#     ecl = "L",
#     hjust = "c",
#     vjust = "c"
#   ))
# 
#   plot(qr_code(link ,
#         ecl = "Q") %>%
#   qrcode::add_logo(
#     logo = "images/cfg-logo-new.png",
#     ecl = "L",
#     hjust = "c",
#     vjust = "c"
#   ))
# 
# }


```

<br>


#### *CLICK THRU* to donate or share

Table below updated on `r format(lubridate::now("UTC") - hours(8), "%B %d, %Y")` at `r paste0(format(lubridate::now("UTC") - hours(8), "%I:%M %p"), " PST") `



```{r final table}
#| column: screen

chuffed_links <- tibble(
  link = "https://chuffed.org/project/artistmohammedalassar",
  link_text = "Mohammed and his wife",
  total_num_donations = NA,
  currency_abv = "USD",
  amount_raised_num = NA,
  percent_of_goal = 0.1667,
  daily_change = NA
)

link_text <- final_table %>%
  dplyr::bind_rows(chuffed_links) %>% 
  dplyr::pull(link_text) 

# format(lubridate::now(), "%B %d, %Y")
# format(lubridate::now(), "%I:%M %p %Z")


final_table %>% 
  dplyr::bind_rows(
    chuffed_links
  ) %>% 
  dplyr::select(-c(link_text)) %>% 
  # dplyr::relocate(uuid, .before = link) %>% 
  gt(
    # rowname_col = "row_n"
    ) %>%
  gt::fmt_url(
    columns = link, 
    label = link_text,
    color = "#fe1a2f"
    # as_button = TRUE,
    # button_fill = "#fe1a2f",
    # button_width = px(95),
    # button_outline = "black"
  ) %>% 
  gt::tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(
      columns = everything()
    )
  ) %>%   
  gt::cols_width(
    total_num_donations ~ px(80),
    daily_change ~ px(80)
  ) %>% 
  gt::sub_missing(
    columns = everything(),
    rows = everything(),
    missing_text = ""
  ) %>% 
  gt::fmt_currency(
    columns = c(amount_raised_num, daily_change),
    currency = from_column(column = "currency_abv"),
    decimals = 0
  ) %>% 
  # gt::fmt_percent(columns = percent_of_goal,
  #                 decimals = 0) %>%
  gtExtras::gt_plt_bar_pct(
    column = percent_of_goal,
    labels = TRUE,
    scaled = TRUE,
    fill = "#01e2b4",
    height = 26,
    width = 132,
    font_style = "bold",
    font_size = "13px",
    decimals = 0,
    label_cutoff = 0
  ) %>%
  gt::cols_hide(
    c(currency_abv)
  ) %>%
  # gt::tab_spanner(
  #   columns = c(total_num_donations_24_hours, money_raised_24_hours),
  #   label = paste0("Within the last 24 hours"),
  #   id = "24_hours"
  # ) %>% 
  # gt::tab_spanner(
  #   columns = c(money_raised_last_20:num_days_last_20),
  #   label = "20 most recent donations",
  #   id = "20_donations"
  # ) %>%   
  # gt::tab_spanner(
  #   columns = c(total_num_donations, amount_raised_num, percent_of_goal),
  #   label = "Campaign totals"
  # ) %>%     
  gt::tab_style(
    style = list(
      cell_borders(
        side = c("left", "right"),
        color = "#f4f4f4"
      )
    ),
    locations = cells_body(
      columns = c(total_num_donations, amount_raised_num, percent_of_goal)
    )
  ) %>% 
  gt::cols_align(
    align = "right",
    columns = total_num_donations
  ) %>% 
  ### ADD A FOOTNOTE HERE!!!
  # tab_footnote(
  #   footnote = "Information from these columns represents the 24 hour perido between date (do a paste0 of dates here",
  #   locations = cells_column_labels(columns = c(total_num_donations_24_hours,
  #                                               money_raised_24_hours))
  # ) %>% 
  gt::cols_label(
    # campaign_title = "Fundraiser",
    total_num_donations = "Number of total donations",
    amount_raised_num = "Total amount raised",
    percent_of_goal = "Percent of goal reached",
    # total_num_donations_24_hours = paste0("Number of donations on ", format(lubridate::now("UTC") - lubridate::days(1), "%B %d")),
    daily_change = paste0("Amount raised on ", format(lubridate::now("UTC") - lubridate::days(1), "%B %d")),
    # uuid = "QR Code",
    link = "Link to Fundraiser"
    # total_num_donations_last_20 = "Number of donations",
    # money_raised_last_20 = "Amount raised",
    # num_days_last_20 = "# of days between last 20 donations"
  ) %>% 
  gt::tab_options(table.width = pct(100),
                      # table.font.color = "#FFFFFF",
    table.background.color = "#FFFFFF",
    table.font.size = px(13),
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    # table_body.hlines.color = "transparent",
    table_body.border.bottom.color = "transparent",
    column_labels.border.bottom.color = "transparent",
    column_labels.border.top.color = "transparent") %>% 
  gt::opt_css(
    css = "
    table tr:nth-child(odd) {
      background-color: white;
    }
      
    table tr:hover {
      background-color: lightgrey;
    }
    
    .cell-output-display {
      overflow-x: unset !important;
    }
    
    div#custom {
      overflow-x: unset !important;
      overflow-y: unset !important;
    }
    
    #custom .gt_col_heading {
      position: sticky !important;
      top: -5px !important;
      z-index: 10 !important;
    }
    "
  )



```

<br>

#### Total amount raised from all the current fundraising campaigns

```{r totals}
#| column: screen
#| color: primary
#| theme: primary


vbs <- list(
  value_box(
    title = paste0("Total amount raised in Euros from ", num_funds_euro, " funds:"),
    # theme = "orange", # doesnt work must change this in scss file
    value = paste0("€", sum_all_donations_in_eur),
    icon = bs_icon("cash")
  ),
  value_box(
    title = paste0("Total amount raised in US Dollars from ", num_funds_usd, " funds:"),
    # theme = "#01e2b4",
    value = paste0("$", sum_all_donations_in_usd),
    icon = bs_icon("bank")
  ),
  value_box(
    title = paste0("Total amount raised in Canadian Dollars from ", num_funds_cad, " funds:"),
    # theme = "#01e2b4",
    value = paste0("$", sum_all_donations_in_cad),
    icon = bs_icon("bank")
  ),  
  value_box(
    title = paste0("Total amount raised in British Pounds from ", num_funds_gbp, " funds:"),
    # theme = "primary",
    value = paste0("£", sum_all_donations_in_gbp),
    icon = "cash"
  ),
  value_box(
    title = paste0("Total amount raised in Swedish krona from ", num_funds_sek, " funds:"),
    # theme = "light",
    value = paste0("kr", sum_all_donations_in_sek),
    icon = "cash"
  ),
  value_box(
    title = paste0("Total amount raised in Norwegian krone from ", num_funds_nok, " funds:"),
    # theme = "light",
    value = paste0("kr", sum_all_donations_in_nok),
    icon = "cash"
  )  
)

layout_column_wrap(
  width = "250px",
  fixed_width = TRUE,
  !!!vbs
)

```


#### Amount raised on `r format(lubridate::now("UTC") - lubridate::days(1), "%B %d, %Y")`

```{r totals 24}
#| column: screen
#| color: primary
#| theme: primary


vbs1 <- list(
  value_box(
    title = paste0("Amount raised in Euros on ", format(lubridate::now("UTC") - lubridate::days(1), "%B %d, %Y"),
                   " from ", num_funds_euro_24, " funds:"),
    # theme = "orange", # doesnt work must change this in scss file
    value = paste0("€", sum_all_donations_in_eur_24),
    icon = bs_icon("cash")
  ),
  value_box(
    title = paste0("Amount raised in US Dollars on ", 
                   format(lubridate::now("UTC") - lubridate::days(1), "%B %d, %Y"),
                   " from ", num_funds_usd_24, " funds:"),
    # theme = "orange", # doesnt work must change this in scss file
    value = paste0("$", sum_all_donations_in_usd_24),
    icon = bs_icon("cash")
  ),  
  value_box(
    title = paste0("Amount raised in Canadian Dollars on ", 
                   format(lubridate::now("UTC") - lubridate::days(1), "%B %d, %Y"),
                   " from ", num_funds_cad_24, " funds:"),
    # theme = "orange", # doesnt work must change this in scss file
    value = paste0("$", sum_all_donations_in_cad_24),
    icon = bs_icon("cash")
  ),    
  value_box(
    title = paste0("Amount raised in British Pounds on ", 
                   format(lubridate::now("UTC") - lubridate::days(1), "%B %d, %Y"),
                   " from ", num_funds_gbp_24, " funds:"),
    # theme = "orange", # doesnt work must change this in scss file
    value = paste0("£", sum_all_donations_in_gbp_24),
    icon = bs_icon("cash")
  ),    
  value_box(
    title = paste0("Amount raised in Swedish krona on ", 
                   format(lubridate::now("UTC") - lubridate::days(1), "%B %d, %Y"),
                   " from ", num_funds_sek_24, " funds:"),
    # theme = "orange", # doesnt work must change this in scss file
    value = paste0("kr", sum_all_donations_in_sek_24),
    icon = bs_icon("cash")
  ),
  value_box(
    title = paste0("Amount raised in Norwegian krone on ", 
                   format(lubridate::now("UTC") - lubridate::days(1), "%B %d, %Y"),
                   " from ", num_funds_nok_24, " funds:"),
    # theme = "orange", # doesnt work must change this in scss file
    value = paste0("kr", sum_all_donations_in_nok_24),
    icon = bs_icon("cash")
  )  
)

layout_column_wrap(
  width = "250px",
  fixed_width = TRUE,
  !!!vbs1
)

```


[Link to latest currency conversion rates](https://www.bloomberg.com/markets/currencies)

