---
title: "FAQs"
format:
  html:
    toc: false
    link-external-newwindow: true
---

### What is Creators for Gaza?

**We are a SWANA-led global collective fundraising for Palestinians we know and love in Gaza.** Each of our campaigns supports someone we personally know, or are connected to locally. With our collective efforts, we have raised more than \$2 million for our 50 families. You can make a difference, and build solidarity with people in Gaza.

### Who is a Creator for Gaza?

**A creator is someone who fundraises for one of our families in Gaza.** By signing up to become a creator with us, you will be taking on one of our family campaigns and committing to consistently amplifying their campaign.

### What happens after I sign up?

You will be paired with a specific family and put in touch with their campaign contact. You will create a plan to fundraise for this family. We will send links, resources, and instructions to help support you. You will have the option to join a signal chat with other Creators also doing this work. You don’t have to figure out how to reinvent a wheel, you just have to plug into the work already being done.

### How can I fundraise for a family in Gaza?

Folks have been getting so creative! **Your skillset and imagination are the limit.**

In Person:

-   Bake Sales

-   Game nights

-   Movie screenings

-   Benefit Shows

-   Art markets

-   Classes and Skill Shares

-   Contributing a portion of sales for something you already make

-   Services you provide

Online:

-   Raffles and silent auctions

-   Fundraiser Merch items like tshirts, art prints, etc

-   Posts to social media, blogs, email lists and websites highlighting a family's campaign link to solicit contributions

Please check [our instagram](https://www.instagram.com/creatorsforgaza/ "https://www.instagram.com/creatorsforgaza/") for examples of how others have done this. There is a place in this work for quite literally everyone, regardless of whether you consider yourself to be “creative”.

Your goal is to bring attention to the campaign that highlights that our Palestinian families in Gaza are not numbers. You can help our families feel seen and amplify their stories. While we can be a sounding board for ideas, you will be working on this goal independently or with your existing social circles.

### How do I join Creators for Gaza?

[Sign up here](https://cryptpad.fr/form/#/2/form/view/8nuW2QzSR+5B0zlcKhMcJnGVnz-Ik+spwbSjYNyrmHc/ "CREATOR SIGN UP FORM")!

### I filled out the form, but I never got an assignment, what do I do?

First, please check your spam and/or junk folder. We try to send assignments on Monday, Wednesday, and Friday. If you have not heard back from us within a week, please feel free to email us: creatorsforgaza\@proton.me

### I got my assignment, but haven't heard back from my campaign contact, what do I do?

Your campaign contact **may** respond to your initial campaign assignment email with updates, more images, or other info to share with you. **However, please do not wait to hear back from your contact before starting or continuing to fundraise. Please be mindful that in some cases, your campaign contact and family assignment are the same person.** While we need to be accessible and responsive, our campaign contacts are not always able to, nor do they owe us timely responses (particularly if they are a Palestinian in Gaza).

### Can’t quite commit to being a creator?

**First, ask yourself why not?** We all make time for things that are important to us, and we have to fundraise because we fail to stop The Genocide. If you **truly** cannot commit to becoming a creator, help support creators and families on your own by printing and disseminating [resources](https://drive.google.com/drive/folders/1DP0FoIJ5HYkfXWEFCutYxwSzBlqf1tGA "Resources folder"). Many creators have volunteered their time and talents, you can help by passing out flyers, zines and handbills around your neighborhood and local businesses. If you are on Instagram, it is helpful to engage with content on our page: like, comment, share to stories and messages, etc.

### How do I add a family to your list/database?

**We are not currently adding new families**. We are still fundraising for the families we are committed to. We understand that there is great need and lots of urgency, but we believe in commitment and consistency in supporting the folks we have taken on. We do not currently have the capacity to support more families.

### How are your campaigns verified?

We know the folks we support through personal connections of family and community. The families we support know best what they need and we offer them that support as we can.

### Why are you still fundraising? Hasn’t a ceasefire been called?

All of Gaza's infrastructure has been destroyed. There are limited supplies and aid getting in to Gaza. Our families have so far managed to survive The Genocide, but the "ceasefire" has involved uninterrupted bombings and a blockade on many essentials, leading to massive shortages. Every other ceasefire has been broken. The loss of infrastructure in Gaza is unparalleled in modern history. Our families’ homes, workplaces, schools, hospitals, and infrastructure have been destroyed by the occupation, using american bombs. Their friends and family members have been murdered by the occupation forces. Our tax dollars paid for this. **Continuing to fundraise for their needs to be met is quite literally the least we can and should do.**

### What are families in Gaza using the money for?

Without the ability to evacuate, our friends in Gaza are using the money from their campaigns to survive. In the unlikely event that a family is approved for evacuation, they will use the funds for that.

### Which family/campaign should I donate to?

Any! We are connected to each of these families, and every one is in dire need of help. Each of these families is someone we know personally, or is connected to our people.

### How does the money raised reach the families in Gaza?

The gofundme/chuffed campaign organizer coordinates and electronically transfers funds directly to the family. Our job is to raise funds.

### Can you set up a gofundme/fundraiser for my family?

We do not create fundraisers. Our role is to amplify fundraisers that already exist, from people and families we are connected to.
